export const types = {
    IS_LOADED: 'IS_LOADING_TYPE',
    IS_LOADING: 'IS_LOADING',
    RE_PAGE: 'RE_PAGE',
    ADD_POKEMONS: 'ADD_POKEMONS',
    GET_INFO_ABOUT_POKEMON: 'GET_INFO_ABOUT_POKEMON',
    GET_NAMES: 'GET_NAMES',
    GET_ABILITIES: 'GET_ABILITIES'
}